### ISSUE TITLE
To fix a error: children?.includes is not a function

### ISSUE THREAD

**Issue by vitakili** [anetaj/strapi-plugin-multi-tenant#5]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `strapi-plugin-multi-tenant@1.0.4` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/strapi-plugin-multi-tenant/server/content-types/user-group/lifecycles.js b/node_modules/strapi-plugin-multi-tenant/server/content-types/user-group/lifecycles.js
index 4a74647..af48222 100644
--- a/node_modules/strapi-plugin-multi-tenant/server/content-types/user-group/lifecycles.js
+++ b/node_modules/strapi-plugin-multi-tenant/server/content-types/user-group/lifecycles.js
@@ -4,7 +4,7 @@ module.exports = {
   beforeCreate(event) {
     const { parent, children } = event.params.data;
 
-    if (children?.includes(parent)) {
+    if (children?.includes && children?.includes(parent)) {
       throw new ValidationError("User group cannot be both child and parent");
     }
   },
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Sefibrah** [comment]
Hey thank you for your answer, this worked! The steps are pretty much very well explained in [this repo](https://github.com/ds300/patch-package) and hinted at by you @vitakili, but here are the specific steps for the other curious folk out there:

In package.json add this:
```
  "scripts": {
    //...
    "postinstall": "patch-package"
  },
```

Not sure if one or both of these needed to be ran, so I've ran both of these:
```
npm i patch-package
yarn add patch-package postinstall-postinstall
```

Then go to ```node_modules/strapi-plugin-multi-tenant/server/content-types/user-group/lifecycles.js```, and make the following changes inspired by this [PR](https://github.com/anetaj/strapi-plugin-multi-tenant/pull/3):
```
const { ValidationError } = require("@strapi/utils").errors;

module.exports = {
  beforeCreate(event) {
    const { parent, children } = event.params.data;
    if (children?.includes && children?.includes(parent)) {
      throw new ValidationError("User group cannot be both child and parent");
    }
  },
  beforeUpdate(event) {
    const { parent, children } = event.params.data;
    const { id } = event.params.where;

    if (children?.includes && children?.includes(parent)) {
      throw new ValidationError("User group cannot be both child and parent");
    }

    if (children?.includes && (children?.includes(id) || parent === id)) {
      throw new ValidationError("User group cannot be its own child or parent");
    }
  },
};
```

Then run:
```
yarn patch-package strapi-plugin-multi-tenant
```

And now it works. A new ```patches``` folder got generated, which I presume will always be overriding the ```strapi-plugin-multi-tenant``` with the newly created patch.

I guess that this is a nice work-around until the changes are persisted in the npm registry...

**Comment by SVronskiy** [comment]
Hello, @Sefibrah !

Fix works for me, thank you!

**Comment by SVronskiy** [comment]
Hello!

I'm getting another error after applying this fix. When I'm calling /api/workspaces or /api/workspaces/1 or /api/notes or /api/notes/1 with same error 500:
```
[2023-04-15 00:04:13.983] error: Undefined attribute level operator id
Error: Undefined attribute level operator id
    at processAttributeWhere (/Users/user/repos/project/backend/src/node_modules/@strapi/database/lib/query/helpers/where.js:86:13)
    at processWhere (/Users/user/repos/project/backend/src/node_modules/@strapi/database/lib/query/helpers/where.js:148:45)
    at /Users/user/repos/project/backend/src/node_modules/@strapi/database/lib/query/helpers/where.js:108:31
    at Array.map (<anonymous>)
    at Object.processWhere (/Users/user/repos/project/backend/src/node_modules/@strapi/database/lib/query/helpers/where.js:108:18)
    at Object.processState (/Users/user/repos/project/backend/src/node_modules/@strapi/database/lib/query/query-builder.js:317:29)
    at Object.getKnexQuery (/Users/user/repos/project/backend/src/node_modules/@strapi/database/lib/query/query-builder.js:354:12)
    at Object.execute (/Users/user/repos/project/backend/src/node_modules/@strapi/database/lib/query/query-builder.js:475:25)
    at Object.findMany (/Users/user/repos/project/backend/src/node_modules/@strapi/database/lib/entity-manager/index.js:189:70)
    at runMicrotasks (<anonymous>)
```

I've uploaded code here https://github.com/SVronskiy/strapi-plugin-multi-tenant-example

**Comment by SVronskiy** [comment]
Hello, 
My last error was fixed by changing api/workspace/content-types/workspace/schema.json from:
```
    "multi_tenant_user_group": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "plugin::multi-tenant.user-group",
      "inversedBy": "workspaces"
    },
```
to:
```
    "userGroup": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "plugin::multi-tenant.user-group",
      "inversedBy": "workspaces"
    }
```

Plugin depend on name of related field userGroup, it should be exactly "userGroup".
