### ISSUE TITLE
inversedBy attribute cars not found target plugin::multi-tenant.user-group

### ISSUE THREAD

**Issue by Sefibrah** [anetaj/strapi-plugin-multi-tenant#8]
Strapi version: **v4.7.0-beta.0**
strapi-plugin-multi-tenant version: **1.0.4**

**Full error message:**
```
[2023-03-13 17:13:07.040] debug: ⛔️ Server wasn't able to start properly.
[2023-03-13 17:13:07.042] error: Error on attribute userGroup in model car(api::car.car): inversedBy attribute cars not found target plugin::multi-tenant.user-group
Error: Error on attribute userGroup in model car(api::car.car): inversedBy attribute cars not found target plugin::multi-tenant.user-group
    at createMetadata (/Users/ibrahimsefer/Local Documents/Clients/seferware/swrc/swrc-api-phoenix/node_modules/@strapi/database/lib/metadata/index.js:83:15)
    at new Database (/Users/ibrahimsefer/Local Documents/Clients/seferware/swrc/swrc-api-phoenix/node_modules/@strapi/database/lib/index.js:19:21)
    at Function.Database.init (/Users/ibrahimsefer/Local Documents/Clients/seferware/swrc/swrc-api-phoenix/node_modules/@strapi/database/lib/index.js:116:14)
    at Strapi.bootstrap (/Users/ibrahimsefer/Local Documents/Clients/seferware/swrc/swrc-api-phoenix/node_modules/@strapi/strapi/lib/Strapi.js:417:30)
    at Strapi.load (/Users/ibrahimsefer/Local Documents/Clients/seferware/swrc/swrc-api-phoenix/node_modules/@strapi/strapi/lib/Strapi.js:488:16)
    at async Strapi.start (/Users/ibrahimsefer/Local Documents/Clients/seferware/swrc/swrc-api-phoenix/node_modules/@strapi/strapi/lib/Strapi.js:217:9)
```
I already found a solution, but wanted to share it.

**Context:**
I have a car content-type schema, and as it's mentioned in the [documentation,](https://github.com/anetaj/strapi-plugin-multi-tenant#strapi-model) I've added this to it:
```
{
  "kind": "collectionType",
  "collectionName": "cars",
  "info": {
    "singularName": "car",
    "pluralName": "cars",
    "displayName": "Car",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    // my other car content-type attributes
    "userGroup": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "plugin::multi-tenant.user-group",
      "inversedBy": "cars"
    }
  }
}
```
However, this just gives me the error above. If somehow you don't get the error mentioned, then I guess you are very very lucky or I'm just a silly documentation reader.

**My solution:**
go to ```index.js```, and extend the ```plugin::multi-tenant.user-group``` content-type like this:
```
"use strict";
module.exports = {
  /**
   * An asynchronous register function that runs before
   * your application is initialized.
   *
   * This gives you an opportunity to extend code.
   */
  register({ strapi }) {
    strapi.contentType("plugin::multi-tenant.user-group").attributes = {
      ...strapi.contentType("plugin::multi-tenant.user-group").attributes,
      cars: {
        type: "relation",
        relation: "oneToMany",
        target: "api::car.car",
        mappedBy: "userGroup",
      },
    };
  },

  /**
   * An asynchronous bootstrap function that runs before
   * your application gets started.
   *
   * This gives you an opportunity to set up your data model,
   * run jobs, or perform some special logic.
   */
  async bootstrap(/*{ strapi }*/) {}
};
```

Now ```api::car.car``` and ```plugin::multi-tenant.user-group``` have a manyToOne relationship :)

**Comment by thomasbnt** [comment]
Hello @Sefibrah ! Seems I've got the same issue.
I changed a relation from a Collection, and the server don't want to reload. I've got this error :

```bash
✔ Creating admin (11225.103291988373ms)
Error: inversedBy attribute ks not found target api::a.a
    at createJoinTable (/home/strapi/node_modules/@strapi/database/dist/index.js:2218:13)
    at createManyToOne (/home/strapi/node_modules/@strapi/database/dist/index.js:1934:5)
    at createRelation (/home/strapi/node_modules/@strapi/database/dist/index.js:2249:14)
    at createMetadata (/home/strapi/node_modules/@strapi/database/dist/index.js:2327:11)
    at new Database (/home/strapi/node_modules/@strapi/database/dist/index.js:6105:21)
    at Database.init (/home/strapi/node_modules/@strapi/database/dist/index.js:6100:16)
    at Strapi.bootstrap (/home/strapi/node_modules/@strapi/strapi/dist/Strapi.js:365:39)
    at Strapi.load (/home/strapi/node_modules/@strapi/strapi/dist/Strapi.js:419:16)
    at async Object.develop (/home/strapi/node_modules/@strapi/admin/dist/_chunks/index-cce8ecb6.js:1160:28)
    at async develop (/home/strapi/node_modules/@strapi/admin/dist/_chunks/develop-69e28e61.js:52:5)
[ERROR]  There seems to be an unexpected error, try again with --debug for more information

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                           │
│   Error: Error on attribute n in model k(api::k.k): inversedBy attribute anot found target api::a.a   │
│       at createMetadata (/home/strapi/node_modules/@strapi/database/dist/index.js:2334:17)                                                │
│       at new Database (/home/strapi/node_modules/@strapi/database/dist/index.js:6105:21)                                                  │
│       at Database.init (/home/strapi/node_modules/@strapi/database/dist/index.js:6100:16)                                                 │
│       at Strapi.bootstrap (/home/strapi/node_modules/@strapi/strapi/dist/Strapi.js:365:39)                                                │
│       at Strapi.load (/home/strapi/node_modules/@strapi/strapi/dist/Strapi.js:419:16)                                                     │
│       at async Object.develop (/home/strapi/node_modules/@strapi/admin/dist/_chunks/index-cce8ecb6.js:1160:28)                            │
│       at async develop (/home/strapi/node_modules/@strapi/admin/dist/_chunks/develop-69e28e61.js:52:5)                                    │
│       at async Command.parseAsync (/home/strapi/node_modules/commander/lib/command.js:923:5)                                              │
│       at async Module.runStrapiCommand (/home/strapi/node_modules/@strapi/strapi/dist/commands/index.js:124:3)                            │
│                                                                                                                                           │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Done in 14.97s.
```
_Legend : 
n is one collection
k is one collection
ks is the k collection but plurial._

~~How do you find the good `index.js` file?~~ Find into `src/`. But still error when I would like to "link" both. I don't know enough about Strapi to be able to say things like that. 🤣
